FROM python:3.11

WORKDIR /app
RUN pip install --upgrade pip setuptools

# 安装项目依赖（假设 requirements.txt 在项目根目录）
COPY scatter/requirements.txt ./
RUN pip install -r requirements.txt

# 下载 nltk 需要的资源
RUN python -c "import nltk; nltk.download('stopwords')"

# 入口命令由 docker-compose.yml 指定，此处不设置 CMD
